version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "launch-jest"
          command: "npm i jest && jest"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
